### ISSUE TITLE
TypeError bug in callbacks.py 

### ISSUE THREAD

**Issue by kieutrang1211** [ivo-1/bomberman_rl#13]
When executing `python3 main.py play --my-agent coli_agent --train 1 --n-rounds 1000 --no-gui` the following error can be obeserved:
 
 ```sh
 Traceback (most recent call last):
  File "main.py", line 265, in <module>
    main()
  File "main.py", line 253, in main
    world_controller(
  File "main.py", line 73, in world_controller
    world.do_step(user_input)
  File "/home/students/vu/FML/bomberman_rl/environment.py", line 207, in do_step
    self.send_game_events()
  File "/home/students/vu/FML/bomberman_rl/environment.py", line 563, in send_game_events
    a.wait_for_game_event_processing()
  File "/home/students/vu/FML/bomberman_rl/agents.py", line 191, in wait_for_game_event_processing
    self.backend.get("game_events_occurred")
  File "/home/students/vu/FML/bomberman_rl/agents.py", line 328, in get
    return self.get_with_time(expect_name, block, timeout)[0]
  File "/home/students/vu/FML/bomberman_rl/agents.py", line 340, in get_with_time
    raise result
  File "/home/students/vu/FML/bomberman_rl/agents.py", line 296, in process_event
    event_result = getattr(module, event_name)(self.fake_self, *event_args)
  File "/home/students/vu/FML/bomberman_rl/agent_code/coli_agent/train.py", line 91, in game_events_occurred
    new_state = state_to_features(self, new_game_state, self.history)
  File "/home/students/vu/FML/bomberman_rl/agent_code/coli_agent/callbacks.py", line 549, in state_to_features
    f"Shortest path feature says: {_shortest_path_feature(self, game_state)}"
  File "/home/students/vu/FML/bomberman_rl/agent_code/coli_agent/callbacks.py", line 315, in _shortest_path_feature
    return _get_action(self_coord, best[0])
  File "/home/students/vu/FML/bomberman_rl/agent_code/coli_agent/callbacks.py", line 217, in _get_action
    goal_coord = shortest_path[1]  # 0th element is self_coord
TypeError: 'NoneType' object is not subscriptable
```

Possibly due to the weird `unreachable crate` edge case the variable `crates_coordinates` remains empty and the for loop won't be reached. The `best = (None, np.inf)` variable remains unchanged and leads in `_get_action` - when giving `shortest_path` the variable `best[0]` (of type None in this case) - to the `TypeError` because we are trying to access [1] of `None` with `shortest_path[1]`.

**Comment by kieutrang1211** [comment]
[TypeError.txt](https://github.com/ivo-1/bomberman_rl/files/8259091/TypeError.txt)
Here the tail of the log file.

**Comment by ivo-1** [comment]
<img width="201" alt="Screenshot 2022-03-16 at 01 40 38" src="https://user-images.githubusercontent.com/52181822/158572208-83fba260-e856-4287-93c9-601b68d171ae.png">

This is what happened.
